#!/bin/sh

#実行時にコマンドラン引数の数が1でなければ終了
if [ $# -ne 1 ]; then
    echo "Usage: $0 <NewFileName>" 1>&2
    exit 1
fi

# 生成するファイル名
# $1に".py"が含まれていても、含まれていなくても正しく動作する
head=${1##*[0-9_]}
head=${head%\.py}
fileName="${1%\.py}.py"

# ファイルに書き込むテンプレート
str=$(cat <<-EOF
# -*- coding: utf-8 -*-

def $head():
    

def main():
    $head()

if __name__ == '__main__':
    main()
EOF
)

# ファイルにテンプレートを書き込む
echo "$str" > "./$fileName" && echo "Created new file!: $fileName"
